name: Add new package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package name to add'
        required: true
        default: 'drupal/some_module'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Add Package
        run: composer require ${{ github.event.inputs.package }}

      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add composer.json composer.lock
          git commit -m "Added package ${{ github.event.inputs.package }}"
          git push

