name: Add package with optional version

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package name to add, e.g., "drupal/some_module"'
        required: true
      version:
        description: 'Optional version of the package, e.g., "1.2.3"'
        required: false
        default: ''

jobs:
  add_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Add Specified Package
        run: |
          PACKAGE_NAME="${{ github.event.inputs.package }}"
          PACKAGE_VERSION="${{ github.event.inputs.version }}"
          if [ -z "$PACKAGE_VERSION" ]; then
            composer require $PACKAGE_NAME
          else
            composer require $PACKAGE_NAME:$PACKAGE_VERSION
          fi

      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add composer.json composer.lock
          git commit -m "Added package $PACKAGE_NAME with version $PACKAGE_VERSION"
          git push
