name: Update Aqto Project with latest build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_aqto_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout aqto_upstream
        uses: actions/checkout@v3

      - name: Clone aqto_project
        env:
          GH_TOKEN: ${{ secrets.AQTO_PROJECT_GH_TOKEN }}
        run: |
          git clone https://github.com/twfahey1/aqto_project.git
          cd aqto_project
          git remote set-url origin https://twfahey1:${{ secrets.AQTO_PROJECT_GH_TOKEN }}@github.com/twfahey1/aqto_project.git

      - name: Update the aqto_project via composer update
        working-directory: aqto_project
        run: |
          composer update --no-progress --no-interaction 
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update aqto_project with latest changes from aqto_upstream"
            # Use the token and GitHub CLI to authenticate and push changes
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            echo $GH_TOKEN | gh auth login --with-token
            git push
          else
            echo "No changes to commit"
          fi